-- Tabela: BLOG POSTS
-- Armazena os artigos gerados por IA para o Blog.
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    image_url TEXT,
    category TEXT DEFAULT 'Saúde Mental Infantil',
    meta_title TEXT,
    meta_description TEXT,
    is_published BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE,
    target_region TEXT DEFAULT 'Cajazeiras, Salvador - BA'
);

-- Habilitar RLS
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Public can read published posts" ON public.blog_posts;
CREATE POLICY "Public can read published posts" ON public.blog_posts FOR SELECT USING (is_published = true);

DROP POLICY IF EXISTS "Admins can manage posts" ON public.blog_posts;
CREATE POLICY "Admins can manage posts" ON public.blog_posts ALL TO authenticated USING (true);

-- Permissões para usuários anônimos lerem (PostgREST)
GRANT SELECT ON TABLE public.blog_posts TO anon;
GRANT ALL ON TABLE public.blog_posts TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE blog_posts_id_seq TO anon, authenticated;
