-- =========================================================================================
-- MASTER SQL SCHEMA - LÉIA NEVES APP (PSICOPEDAGOGIA)
-- Este arquivo reune a criação de todas as tabelas, permissões (RLS) e dados de exemplo.
-- Para usar: copie e cole todo este código na aba "SQL Editor" do Supabase e clique em "Run".
-- =========================================================================================

-- ==============================================================================
-- 1. CRIAÇÃO DAS TABELAS (SCHEMAS)
-- ==============================================================================

-- Tabela: AGENDAMENTOS (Appointments)
-- Guarda os pedidos de consulta vindos do site principal (Fila de Espera/Agendamento).
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    parent_name TEXT NOT NULL,         
    child_name TEXT NOT NULL,          
    child_age INTEGER,                 
    email TEXT NOT NULL,               
    phone TEXT NOT NULL,               
    concern TEXT,                      
    preferred_date DATE NOT NULL,      
    preferred_time TEXT NOT NULL,      
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
    google_event_id TEXT,              
    notes TEXT,                         
    cpf TEXT                           -- Adicionado coluna de CPF
);

-- Tabela: DISPONIBILIDADE (Availability Slots - Opcional)
-- Caso queira gerenciar blocos de horário fixos ao invés de usar só o Calendário do Google.
CREATE TABLE IF NOT EXISTS public.availability_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INTEGER,               
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

-- Tabela: PACIENTES (Patients)
-- Guarda o cadastro principal dos pacientes ativos da clínica.
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    child_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    birth_date DATE,
    notes TEXT,
    status TEXT DEFAULT 'active', -- active, archived
    cpf TEXT UNIQUE               -- Adicionado coluna de CPF
);

-- Tabela: DOCUMENTOS DE PACIENTES (Patient Documents)
-- Anexos avulsos (Laudos, exames externos, imagens) enviados ou atrelados ao paciente.
CREATE TABLE IF NOT EXISTS public.patient_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT NOT NULL,
    file_type TEXT 
);

-- Tabela: MODELOS DE DOCUMENTOS (Document Templates)
-- Textos e templates HTML pré-prontos para laudos, informes, encaminhamentos, etc.
CREATE TABLE IF NOT EXISTS public.document_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT
);

-- Tabela: REGISTROS CLÍNICOS / DOCUMENTOS PREENCHIDOS (Clinical Records)
-- O histórico de evolução, sessões e relatórios efetivamente emitidos para o paciente.
CREATE TABLE IF NOT EXISTS public.clinical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE NOT NULL,
    template_id BIGINT REFERENCES public.document_templates(id),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE
);


-- ==============================================================================
-- 2. CRIAÇÃO DOS ÍNDICES DE OTIMIZAÇÃO DE BUSCA
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_appointments_email ON public.appointments(email);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(preferred_date);
CREATE INDEX IF NOT EXISTS idx_patients_cpf ON public.patients(cpf);
CREATE INDEX IF NOT EXISTS idx_appointments_cpf ON public.appointments(cpf);


-- ==============================================================================
-- 3. AJUSTES DE PERMISSÃO / SEGURANÇA (ROW LEVEL SECURITY - RLS)
-- ==============================================================================

-- 3.1 Habilitar RLS em todas as tabelas
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_records ENABLE ROW LEVEL SECURITY;

-- 3.2 Limpar políticas de agendamentos antigas/conflitantes (evitando erro de duplicada)
DROP POLICY IF EXISTS "Allow anonymous inserts" ON public.appointments;
DROP POLICY IF EXISTS "Enable insert for anon" ON public.appointments;
DROP POLICY IF EXISTS "Enable insert for all" ON public.appointments;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.appointments;
DROP POLICY IF EXISTS "Enable select for authenticated only" ON public.appointments;
DROP POLICY IF EXISTS "Enable read for authenticated only" ON public.appointments;
DROP POLICY IF EXISTS "Enable update for authenticated only" ON public.appointments;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.appointments;

DROP POLICY IF EXISTS "Admins can select patients" ON public.patients;
DROP POLICY IF EXISTS "Admins can insert patients" ON public.patients;
DROP POLICY IF EXISTS "Admins can update patients" ON public.patients;
DROP POLICY IF EXISTS "Admins can delete patients" ON public.patients;

DROP POLICY IF EXISTS "Admins can select documents" ON public.patient_documents;
DROP POLICY IF EXISTS "Admins can insert documents" ON public.patient_documents;
DROP POLICY IF EXISTS "Admins can update documents" ON public.patient_documents;
DROP POLICY IF EXISTS "Admins can delete documents" ON public.patient_documents;

DROP POLICY IF EXISTS "Admins can select templates" ON public.document_templates;
DROP POLICY IF EXISTS "Admins can insert templates" ON public.document_templates;
DROP POLICY IF EXISTS "Admins can update templates" ON public.document_templates;
DROP POLICY IF EXISTS "Admins can delete templates" ON public.document_templates;

DROP POLICY IF EXISTS "Admins can select records" ON public.clinical_records;
DROP POLICY IF EXISTS "Admins can insert records" ON public.clinical_records;
DROP POLICY IF EXISTS "Admins can update records" ON public.clinical_records;
DROP POLICY IF EXISTS "Admins can delete records" ON public.clinical_records;

-- ==============================================================================
-- APPOINTMENTS (Agendamentos Públicos)
-- ==============================================================================

-- PERMISSÃO DE INSERÇÃO PÚBLICA (Permitir que form do site adicione)
CREATE POLICY "Enable insert for all users" ON public.appointments FOR INSERT TO public WITH CHECK (true);
-- PERMISSÃO DE LEITURA RESTRITA (Somente painel administrativo logado)
CREATE POLICY "Enable select for authenticated only" ON public.appointments FOR SELECT TO authenticated USING (true);
-- PERMISSÃO DE EDIÇÃO RESTRITA (Mudar status pra conluído etc, só admin logado)
CREATE POLICY "Enable update for authenticated only" ON public.appointments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- Garante que o PostgREST deixe anônimos inserirem
GRANT INSERT ON TABLE public.appointments TO anon;
GRANT USAGE, SELECT ON SEQUENCE appointments_id_seq TO anon, authenticated;

-- ==============================================================================
-- DEMAIS TABELAS (Gerenciamento Interno - Somente Usuários Logados)
-- ==============================================================================

-- Pacientes (Patients)
CREATE POLICY "Admins can select patients" ON public.patients FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can insert patients" ON public.patients FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update patients" ON public.patients FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete patients" ON public.patients FOR DELETE TO authenticated USING (true);

-- Documentos e anexos (Patient Documents)
CREATE POLICY "Admins can select documents" ON public.patient_documents FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can insert documents" ON public.patient_documents FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update documents" ON public.patient_documents FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete documents" ON public.patient_documents FOR DELETE TO authenticated USING (true);

-- Modelos de Relatórios/Laudos (Document Templates)
CREATE POLICY "Admins can select templates" ON public.document_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can insert templates" ON public.document_templates FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update templates" ON public.document_templates FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete templates" ON public.document_templates FOR DELETE TO authenticated USING (true);

-- Registros Clínicos Efetivos (Clinical Records)
CREATE POLICY "Admins can select records" ON public.clinical_records FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can insert records" ON public.clinical_records FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update records" ON public.clinical_records FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete records" ON public.clinical_records FOR DELETE TO authenticated USING (true);


-- ==============================================================================
-- 4. INSERÇÃO DE DADOS INICIAIS (SEED DATA)
-- ==============================================================================

-- Evitar duplicação inserindo apenas se não existir. Como estamos usando ON CONFLICT,
-- vamos garantir que haja uma Constraint temporária apenas para essa verificação ou simplesmente rodar INSERTS limpos.
-- Em vez disso, usaremos INSERT simples pois é a primeira vez (ou templates básicos).

TRUNCATE TABLE public.document_templates RESTART IDENTITY CASCADE;

INSERT INTO public.document_templates (title, category, content) VALUES ('Informe de Acompanhamento', 'Relatórios', '
<div class="text-center mb-8">
    <h3 class="font-bold text-xl text-slate-800">Léia Neves</h3>
    <p class="text-slate-500 text-sm">Psicopedagoga Especializada</p>
    <p class="text-slate-400 text-xs">CBO: [Inserir] | ABPp: [Inserir]</p>
</div>

<h2 class="text-center font-bold text-slate-800 text-lg mb-6">INFORME DE ACOMPANHAMENTO</h2>

<p class="mb-4">Informamos à (instituição, responsável ou interessado) que o paciente (aluno) <strong>[Nome do Paciente]</strong> está recebendo acompanhamento psicopedagógico especializado desde [Data de Início], para avaliação e diagnóstico psicopedagógico.</p>
<p class="mb-4">Este acompanhamento tem como objetivo investigar as dificuldades de aprendizagem e intervir de forma adequada para o desenvolvimento do paciente.</p>
<p class="mb-4">Estamos à disposição para qualquer esclarecimento.</p>
<p class="mb-8">Atenciosamente,</p>
<p class="mb-4">[Local e Data]</p>

<div class="mt-12 text-center">
    <div class="border-t border-slate-300 w-64 mx-auto mb-2"></div>
    <p class="font-bold text-slate-700">Léia Neves</p>
    <p class="text-slate-500 text-sm">Psicopedagoga</p>
</div>
');

INSERT INTO public.document_templates (title, category, content) VALUES ('Ficha de Encaminhamento', 'Encaminhamentos', '
<div class="text-center mb-8">
    <h3 class="font-bold text-xl text-slate-800">Léia Neves</h3>
    <p class="text-slate-500 text-sm">Psicopedagoga Especializada</p>
    <p class="text-slate-400 text-xs">CBO: [Inserir] | ABPp: [Inserir]</p>
</div>

<h2 class="text-center font-bold text-slate-800 text-lg mb-6">ENCAMINHAMENTO</h2>

<p class="mb-4"><strong>Ao(À):</strong> [Nome do Profissional/Especialidade]</p>
<p class="mb-4">Prezado(a) Dr(a),</p>
<p class="mb-4">Encaminho o(a) paciente/aprendente <strong>[Nome do Paciente]</strong>, que apresenta os seguintes dados subjetivos e objetivos mais relevantes ao motivo do encaminhamento (descrever sinais de alerta):</p>

<div class="p-4 bg-slate-50 border border-slate-200 rounded mb-4 italic text-slate-600">
    (Descreva aqui as observações...)
</div>

<p class="mb-4">Estamos à disposição para qualquer esclarecimento.</p>
<p class="mb-8">Atenciosamente,</p>
<p class="mb-4">[Local e Data]</p>

<div class="mt-12 text-center">
    <div class="border-t border-slate-300 w-64 mx-auto mb-2"></div>
    <p class="font-bold text-slate-700">Léia Neves</p>
    <p class="text-slate-500 text-sm">Psicopedagoga</p>
</div>
');

-- FIM DA CONFIGURAÇÃO SQL
