-- =========================================================================================
-- SCRIPT DE CRIAÇÃO DA TABELA DE ANAMNESE E ATUALIZAÇÕES NECESSÁRIAS
-- Cole este script na aba "SQL Editor" do Supabase e clique em "Run"
-- =========================================================================================

-- 1. Criar a tabela para as respostas do formulário de triagem (Anamnese)
CREATE TABLE IF NOT EXISTS public.patient_anamnesis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id BIGINT REFERENCES public.patients(id) ON DELETE CASCADE,
    answers JSONB NOT NULL
);

-- 2. Habilitar segurança a nível de linha (RLS)
ALTER TABLE public.patient_anamnesis ENABLE ROW LEVEL SECURITY;

-- 3. Criar Políticas (Policies)
-- Permitir que qualquer pessoa crie (necessário para o formulário público)
CREATE POLICY "Permitir inserção anônima de anamnese" 
ON public.patient_anamnesis 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Permitir que apenas usuários autenticados (Admin) leiam as anamneses
CREATE POLICY "Permitir leitura de anamnese por admin" 
ON public.patient_anamnesis 
FOR SELECT 
TO authenticated 
USING (true);

-- Permitir que apenas usuários autenticados (Admin) atualizem ou deletem as anamneses
CREATE POLICY "Permitir atualizacao de anamnese por admin" 
ON public.patient_anamnesis 
FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Permitir exclusao de anamnese por admin" 
ON public.patient_anamnesis 
FOR DELETE 
TO authenticated 
USING (true);

-- 4. Opcional: Adicionar patient_id na tabela appointments se não existir
-- (Isso ajuda a linkar o agendamento ao paciente no banco de dados)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'appointments' AND column_name = 'patient_id'
    ) THEN
        ALTER TABLE public.appointments ADD COLUMN patient_id BIGINT REFERENCES public.patients(id) ON DELETE SET NULL;
    END IF;
END $$;
