-- Tabela de Roteiros
CREATE TABLE IF NOT EXISTS public.blog_roadmaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    image_url TEXT,
    category TEXT -- O tema principal do roteiro
);

-- Tabela de Itens do Roteiro (Relacionamento entre Roteiros e Blog Posts)
CREATE TABLE IF NOT EXISTS public.blog_roadmap_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT REFERENCES public.blog_roadmaps(id) ON DELETE CASCADE,
    post_id BIGINT REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    order_index INT NOT NULL,
    UNIQUE(roadmap_id, post_id),
    UNIQUE(roadmap_id, order_index)
);

-- Habilitar RLS
ALTER TABLE public.blog_roadmaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_roadmap_items ENABLE ROW LEVEL SECURITY;

-- Políticas
DROP POLICY IF EXISTS "Public can read roadmaps" ON public.blog_roadmaps;
CREATE POLICY "Public can read roadmaps" ON public.blog_roadmaps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can read roadmap items" ON public.blog_roadmap_items;
CREATE POLICY "Public can read roadmap items" ON public.blog_roadmap_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage roadmaps" ON public.blog_roadmaps;
CREATE POLICY "Admins can manage roadmaps" ON public.blog_roadmaps FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can manage roadmap items" ON public.blog_roadmap_items;
CREATE POLICY "Admins can manage roadmap items" ON public.blog_roadmap_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Permissões
GRANT SELECT ON TABLE public.blog_roadmaps TO anon;
GRANT ALL ON TABLE public.blog_roadmaps TO authenticated;
GRANT SELECT ON TABLE public.blog_roadmap_items TO anon;
GRANT ALL ON TABLE public.blog_roadmap_items TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE blog_roadmaps_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE blog_roadmap_items_id_seq TO anon, authenticated;
