-- CREATE BUSINESS SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.business_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available_days INTEGER[] NOT NULL DEFAULT '{6}', -- Default is Saturday (6)
    available_times TEXT[] NOT NULL DEFAULT '{"09:00", "10:00", "11:00", "14:00", "15:00", "16:00"}',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS
ALTER TABLE public.business_settings ENABLE ROW LEVEL SECURITY;

-- Admins can do everything
CREATE POLICY "Admins can manage business settings" ON public.business_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Public can read
CREATE POLICY "Public can read business settings" ON public.business_settings FOR SELECT TO anon USING (true);
CREATE POLICY "Authenticated can read business settings" ON public.business_settings FOR SELECT TO authenticated USING (true);

-- Insert default row if none exists
INSERT INTO public.business_settings (id, available_days, available_times)
SELECT 1, '{6}', '{"09:00", "10:00", "11:00", "14:00", "15:00", "16:00"}'
WHERE NOT EXISTS (SELECT 1 FROM public.business_settings WHERE id = 1);
