-- =========================================================================================
-- SCRIPT DE CRIAÇÃO DA TABELA DE LEADS DE MARKETING
-- Cole este script na aba "SQL Editor" do Supabase e clique em "Run"
-- =========================================================================================

-- 1. Criar a tabela para Leads (Separada dos pacientes da clínica)
CREATE TABLE IF NOT EXISTS public.marketing_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    parent_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    source TEXT DEFAULT 'website_scheduling',
    wants_marketing BOOLEAN DEFAULT TRUE
);

-- 2. Habilitar segurança a nível de linha (RLS)
ALTER TABLE public.marketing_leads ENABLE ROW LEVEL SECURITY;

-- 3. Criar Políticas (Policies)
-- Permitir inserção anônima (necessário pois o form do site salva sem estar logado)
CREATE POLICY "Permitir inserção anônima de leads" 
ON public.marketing_leads 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Permitir leitura e edição apenas para o Admin (você logado)
CREATE POLICY "Permitir admin gerenciar leads" 
ON public.marketing_leads 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
