-- Create the table for appointments
create table public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  parent_name text not null,
  child_name text not null,
  child_age integer,
  email text not null,
  phone text not null,
  concern text,
  preferred_date date not null,
  preferred_time text not null,
  status text default 'pending'
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.appointments enable row level security;

-- Allow anonymous inserts (since the form is public)
create policy "Allow anonymous inserts"
on public.appointments
for insert
to anon
with check (true);
