-- ==========================================
-- SUPER SQL SETUP FOR LÉIA NEVES APP
-- ==========================================

-- 1. Create the APPOINTMENTS table
-- This table stores all the scheduling requests coming from the website.
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Client/Lead Information
    parent_name TEXT NOT NULL,         -- Nome do Responsável
    child_name TEXT NOT NULL,          -- Nome da Criança
    child_age INTEGER,                 -- Idade da Criança
    email TEXT NOT NULL,               -- Contato de E-mail
    phone TEXT NOT NULL,               -- Contato Telefônico (WhatsApp)
    concern TEXT,                      -- Motivo/Queixa Principal
    
    -- Scheduling Details
    preferred_date DATE NOT NULL,      -- Data desejada
    preferred_time TEXT NOT NULL,      -- Horário desejado
    
    -- Status Management
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
    
    -- Integration Fields (Future Proofing)
    google_event_id TEXT,              -- ID do evento no Google Calendar (para quando integrar)
    notes TEXT                         -- Anotações internas da Léia
);

-- 2. Create the AVAILABILITY table (Optional Helper)
-- Useful if you want to define specific blocks of free time manually in the database
-- instead of just relying on Google Calendar.
CREATE TABLE IF NOT EXISTS public.availability_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INTEGER,               -- 0=Sunday, 1=Monday, etc.
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

-- 3. Security Policies (Row Level Security - RLS)
-- Enable RLS to prevent unauthorized access
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow anyone to INSERT a new appointment (Public Form)
CREATE POLICY "Allow anonymous inserts"
ON public.appointments
FOR INSERT
TO anon
WITH CHECK (true);

-- Policy 2: Allow read access to authenticated users (e.g., You managing the dashboard later)
-- Assuming you might add auth later. For now, we can leave it restrictive or open it to anon if you build an admin panel without auth (Not recommended for production).
-- Ideally, you will integration Supabase Auth later.

-- 4. Utility Indexes
-- Speed up searching by email or phone
CREATE INDEX IF NOT EXISTS idx_appointments_email ON public.appointments(email);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(preferred_date);

-- ==========================================
-- INSTRUCTIONS
-- ==========================================
-- 1. Copy all the content above.
-- 2. Go to Supabase Dashboard -> SQL Editor.
-- 3. Paste and Run.
-- ==========================================
